version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    entrypoint: mosquitto
    command: -c /mosquitto-no-auth.conf
    ports:
      - "1883:1883"

  yokai:
    image: ghcr.io/marcbran/yokai:dev-arm64v8
    depends_on:
      - mqtt
    command: run
    environment:
      YOKAI_BROKER: mqtt:1883
      YOKAI_APP_CONFIG: /src/home.jsonnet
    volumes:
      - ./${TEST_FOLDER}:/src

  cli:
    image: hivemq/mqtt-cli
    command: sub -h mqtt -t '#' -T
    depends_on:
      - mqtt
